export const GET_TICKETS_REQUEST = 'GET_TICKETS_REQUEST';
export const GET_TICKETS_FAILURE = 'GET_TICKETS_FAILURE';
export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS';
export const POST_TICKET_REQUEST = 'POST_TICKET_REQUEST';
export const POST_TICKET_FAILURE = 'POST_TICKET_FAILURE';
export const POST_TICKET_SUCCESS = 'POST_TICKET_SUCCESS'; 